server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  config:
    import: "configserver:http://localhost:8888,optional:file:.env[.properties],optional:file:../../.env[.properties]"
  cloud:
    config:
      fail-fast: true
    gateway:
