server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: notification-service
  config:
    import: "configserver:http://localhost:8888,optional:file:.env[.properties],optional:file:../../.env[.properties]"
  cloud:
    config:
      fail-fast: true
      import-check:
        enabled: ${SPRING_CLOUD_CONFIG_IMPORT_CHECK_ENABLED:false}
