name: volunteer-platform 
services: 
  db: 
    image: postgres:16 
    container_name: volunteer_db 
    environment: 
      POSTGRES_DB: volunteer_db 
      POSTGRES_USER: saas 
      POSTGRES_PASSWORD: hg2u=8:l0gVW:@HA
    ports: 
      - \"5432:5432\" 
    volumes: 
      - db_data:/var/lib/postgresql/data 
volumes: 
  db_data:
