server:
  port: 8081

spring:
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.hibernate.SQL: info
