server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: user-service
  config:
    import: "configserver:http://localhost:8888,optional:file:.env[.properties],optional:file:../../.env[.properties]"
  cloud:
    config:
      fail-fast: true
